// Generates a PR-comment-ready verification summary in Markdown.

import type { Job } from "./types";

export function jobToMarkdown(job: Job): string {
  const icon = (ok: boolean) => (ok ? "✅" : "❌");
  const statusLabel = job.status.toUpperCase();
  const headMatch =
    job.expected_head && job.actual_head
      ? job.actual_head.toLowerCase().startsWith(job.expected_head.toLowerCase()) ||
        job.actual_head.toLowerCase() === job.expected_head.toLowerCase()
      : null;

  const lines: string[] = [];
  lines.push("## Verification");
  lines.push("");
  lines.push(`- **Repo:** \`${job.repo}\``);
  lines.push(`- **Ref:** \`${job.ref}\``);
  lines.push(`- **Expected head:** \`${job.expected_head || "—"}\``);
  lines.push(`- **Actual head:** \`${job.actual_head ? job.actual_head.slice(0, 12) : "—"}\``);
  if (headMatch !== null) {
    lines.push(`- **Head match:** ${icon(headMatch)} ${headMatch ? "matched" : "MISMATCH"}`);
  }
  lines.push(`- **Status:** ${icon(job.status === "success")} ${statusLabel}`);
  lines.push(
    `- **Duration:** ${job.durationMs != null ? formatDuration(job.durationMs) : "—"}`
  );
  if (job.metadata?.pr) lines.push(`- **PR:** #${job.metadata.pr}`);
  if (job.metadata?.purpose) lines.push(`- **Purpose:** ${job.metadata.purpose}`);
  if (job.error) lines.push(`- **Error:** ${job.error}`);
  lines.push("");
  lines.push("### Commands");
  lines.push("");
  for (const c of job.commands) {
    const ok = c.status === "success";
    const mark =
      c.status === "success"
        ? "✅"
        : c.status === "skipped"
        ? "⏭️"
        : c.status === "timeout"
        ? "⏱️"
        : "❌";
    const dur = c.durationMs != null ? ` (${formatDuration(c.durationMs)})` : "";
    const exit = c.exitCode != null ? ` [exit ${c.exitCode}]` : "";
    lines.push(`- ${mark} \`${c.command}\`${dur}${exit}`);
  }
  lines.push("");

  // Key logs: show stderr/last output of the first failed command, plus a tail of successful ones.
  const failed = job.commands.find((c) => c.status === "failed" || c.status === "timeout");
  if (failed) {
    lines.push("### Key logs");
    lines.push("");
    lines.push(`**Failed command:** \`${failed.command}\``);
    lines.push("");
    if (failed.stderr && failed.stderr.trim()) {
      lines.push("<details><summary>stderr</summary>");
      lines.push("");
      lines.push("```");
      lines.push(tail(failed.stderr, 4000));
      lines.push("```");
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }
    if (failed.stdout && failed.stdout.trim()) {
      lines.push("<details><summary>stdout</summary>");
      lines.push("");
      lines.push("```");
      lines.push(tail(failed.stdout, 4000));
      lines.push("```");
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }
  } else if (job.commands.length > 0) {
    const last = job.commands[job.commands.length - 1];
    if (last.stdout && last.stdout.trim()) {
      lines.push("### Key logs");
      lines.push("");
      lines.push("<details><summary>last command stdout</summary>");
      lines.push("");
      lines.push("```");
      lines.push(tail(last.stdout, 4000));
      lines.push("```");
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(`_Generated by Purr Verify MCP · jobId \`${job.jobId}\`_`);
  return lines.join("\n");
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const s = ms / 1000;
  if (s < 60) return `${s.toFixed(1)}s`;
  const m = Math.floor(s / 60);
  const rs = Math.round(s % 60);
  return `${m}m${rs}s`;
}

function tail(s: string, max: number): string {
  if (s.length <= max) return s;
  return `... (truncated)\n${s.slice(-max)}`;
}
