export const VERIFY_MCP_INSTRUCTIONS =
  "Before verification, browser work, or local VPS operator work, call read_operating_guide and health_check. Use purr_browser_doctor before the first browser session. Use purr_work_session_start to pair a managed dev server with Pursr inspect-act-screenshot-diagnostics tools, and always close the session when finished. Use the purr discovery, inspection, environment, and deployment-plan tools for local project work. Use server-owned aliases and profiles when runtime values are needed. Call list_allowed_commands before repository-clone verification. Use mode=auto or async for install/build/lint/typecheck/test. Long-running sync requests are routed to async instead of rejected. Timeout overrides automatically opt into long-run handling up to the operator timeout cap. Read effectiveMode from the response and poll get_verification_job when it is async. Use history summaries and bounded log chunks by default while preserving full evidence access.";

export const VERIFY_OPERATING_GUIDE = {
  name: "Purr Verify MCP Operating Guide",
  version: "2026-07-20-pursr-browser-work-v1",
  serverRole:
    "Use this MCP for repository-clone verification, managed local dev-server and Pursr browser work sessions, plus private VPS project discovery, inspection, generic local command execution, exact-tree verification, snapshots, deployment, service restart, health checks, and rollback. Operator mutations run as durable asynchronous jobs; browser work sessions are explicit live sessions with bounded logs and server-side artifacts. GitHub MCP remains responsible for branches, commits, pull requests, and source-file edits.",
  startupProtocol: [
    "Call read_operating_guide first.",
    "Call health_check to confirm runtime, queue, effective timeout policy, durable history status, and auth mode.",
    "For local VPS work, discover projects or provide an absolute cwd, then inspect the project and runtime before planning deployment.",
    "Inspect environment key presence first; reveal only explicitly requested keys when a value is genuinely required.",
    "Call purr_plan_deployment before future deployment mutations. Phase one returns a plan only.",
    "Use purr_run_command as the generic private escape hatch; argv is preferred and shell execution remains available explicitly.",
    "Call purr_browser_doctor before the first browser workflow to verify Pursr, playwright-core, and a Chrome-compatible executable.",
    "Use purr_work_session_start for npm run dev or equivalent, then use snapshot, act, screenshot, inspect, and diagnostics against the same persistent Pursr browser state.",
    "Use purr_work_session_close when browser work is complete so the browser and managed dev-server process tree are closed cleanly.",
    "Use purr_verify_project to verify the exact local VPS working tree without cloning a disposable workspace.",
    "Use purr_deploy_project with approved=true for snapshot, activation, install, verify, build, restart, health checks, and optional automatic rollback in one durable asynchronous job.",
    "Use purr_get_job_status, purr_get_job_logs, and purr_cancel_job for every local operator job.",
    "Call list_allowed_commands before choosing commands.",
    "Confirm repo, ref, expected_head when available, and command list.",
    "Use create_verification_job with mode=auto or mode=async for install/build/lint/typecheck/test.",
    "For smoke, soak, fork, and live-observation jobs lasting hours, provide explicit command_timeout_ms and job_timeout_ms when needed; timeout overrides automatically opt into long-run handling up to maxLongRunTimeoutMs.",
    "Read requestedMode, effectiveMode, routingReason, and autoRouted from the create response.",
    "Poll get_verification_job until terminal status when effectiveMode is async.",
    "Use search_verification_history, get_verification_summary, and get_job_log_chunk to inspect durable evidence without flooding agent context.",
  ],
  hardRules: [
    "Heavy commands requested in sync mode are routed to async instead of being rejected.",
    "Heavy commands include install, build, lint, typecheck, test, prisma generate, playwright, cypress, vitest, jest, Surfpool start, and CI scripts.",
    "Explicit sync remains available for one short smoke command expected to complete within the transport window.",
    "Valid long-running verification is not blocked merely because it lasts for hours. Smoke, soak, fork, and live-observation jobs are supported up to maxLongRunTimeoutMs when the operator supplies valid timeout overrides.",
    "Queued and running jobs are never removed by history retention. Their durable state remains readable until they reach a terminal result, including cancellation and cleanup evidence.",
    "History summaries and log chunks protect agent context; they do not remove access to full stored job evidence.",
    "Private operator commands, local verification, snapshots, deploys, restarts, health checks, and rollbacks run as durable asynchronous jobs against canonical local project paths.",
    "Browser work reuses the Pursr npm package as the browser engine. Do not duplicate its session, action, screenshot, diagnostics, or browser-discovery implementations inside Verify MCP.",
    "A missing browser degrades a work session to a usable dev-server session with an actionable warning unless browserRequired=true was explicitly requested.",
    "Browser actions may have external side effects. Inspect current state first and keep action batches small enough to read back the result.",
    "Same-project operations are serialized by canonical cwd while unrelated projects may execute concurrently within the shared job limit.",
    "Environment inspection returns key names, source locations, and present or missing state by default. Revealing a value requires explicit requested keys and that response is not stored in history or deployment plans.",
    "Canonical cwd is the project identity for plans and future same-project operation locks; requested and symlink paths remain visible for auditability.",
    "Retry transient read-only MCP transport errors, timeouts, HTTP 429, and HTTP 5xx at most five times with backoff of 2, 4, 8, 16, and 32 seconds.",
    "Do not submit an identical source or test failure repeatedly. Record jobId, command, status, and failure summary; change the source, test, or execution inputs before submitting a new job.",
    "A missing or evicted queued/running job is recorded as VERIFY_RESULT_EVICTED. Continue from fresh state on a later run rather than blindly duplicating the same request.",
    "Never disable, pause, or terminate a recurring schedule because verification is unavailable or failed.",
    "Workspace source and per-job cache are disposable and must be removed after terminal execution. Persisted job history and redacted evidence remain available.",
    "Summarize logs by default. Provide full logs only when requested.",
    "Use GitHub MCP for repository edits, branches, commits, pull requests, comments, and file inspection.",
    "Use Notion only for project context, specs, plans, and audit notes.",
  ],
  executionRouting: {
    defaultMode: "auto",
    shortSingleCommand: "sync",
    longRunningCommand: "async",
    multiCommandAuto: "async",
    explicitAsync: "async",
    heavyExplicitSync: "async_fallback",
    rejectionPolicy: "do_not_reject_valid_heavy_work_only_because_sync_was_requested",
  },
  workspaceLifecycle: {
    sourceWorkspace: "delete_after_job",
    perJobCache: "delete_after_job",
    persistedHistory: "retain",
    orphanCleanup: "startup_and_periodic_janitor",
    cleanupEvidence: ["workspaceRemoved", "cacheRemoved", "workspaceError", "cacheError"],
  },
  historyLifecycle: {
    backend: "sqlite_wal",
    activeJobRetention: "never_evict_queued_or_running",
    terminalEvidence: "durable_and_cursor_paginated",
    defaultAgentView: "summary",
    fullEvidenceAccess: "preserved",
    logAccess: "bounded_chunks_and_search",
  },
  operatorInspection: {
    phase: "private_operator_and_pursr_browser_work",
    defaultRoots: ["/opt", "/srv", "/var/www", "/home", "/root", "/mnt", "/data", "/var/lib", "/usr/local", "/workspace", "/tmp"],
    customRootsEnvironment: "PURR_OPERATOR_ROOTS",
    projectIdentity: "canonical_absolute_cwd",
    runtimeAdapters: ["pm2", "systemd", "docker_compose", "process"],
    projectTypes: ["node", "rust", "python", "go", "docker_compose"],
    environmentSources: ["dotenv", "pm2", "systemd", "docker_compose", "process"],
    defaultEnvironmentView: "key_name_source_and_presence_only",
    revealedValuePersistence: "never",
    mutationToolsAvailable: true,
  },
  safeToolRouting: {
    verifyMcp: [
      "health_check",
      "list_allowed_commands",
      "create_verification_job",
      "get_verification_job",
      "search_verification_history",
      "get_latest_verification",
      "get_verification_summary",
      "compare_verification_jobs",
      "get_job_log_chunk",
      "search_job_logs",
      "purr_list_server_env_aliases",
      "purr_list_server_env_profiles",
      "purr_discover_projects",
      "purr_inspect_project",
      "purr_inspect_runtime",
      "purr_inspect_environment",
      "purr_plan_deployment",
      "purr_run_command",
      "purr_verify_project",
      "purr_create_deploy_snapshot",
      "purr_deploy_project",
      "purr_restart_service",
      "purr_check_health",
      "purr_rollback_deployment",
      "purr_get_job_status",
      "purr_get_job_logs",
      "purr_cancel_job",
      "purr_browser_doctor",
      "purr_work_session_start",
      "purr_work_sessions",
      "purr_work_session_status",
      "purr_work_session_snapshot",
      "purr_work_session_act",
      "purr_work_session_screenshot",
      "purr_work_session_inspect",
      "purr_work_session_diagnostics",
      "purr_work_session_close",
    ],
    githubMcp: ["repository inspection", "branch", "commit", "pull request", "file operations"],
    notion: ["specs", "plans", "audit notes", "project context"],
  },
  defaultVerificationPolicy: {
    mode: "auto",
    logMode: "summary",
    maxIdenticalSourceFailureRetries: 0,
    readOnlyTransportRetries: 5,
    readOnlyBackoffSeconds: [2, 4, 8, 16, 32],
    missingJobStatus: "VERIFY_RESULT_EVICTED",
    explicitCommandTimeoutMs: 600000,
    explicitJobTimeoutMs: 1800000,
    maxLongRunTimeoutMs: 31536000000,
    supportedLongRunExamples: [
      "PurrLiquid fork smoke",
      "Surfpool fork soak",
      "long-lived integration observation",
      "private release verification",
    ],
    recurringScheduleAction: "continue",
    pollWhenEffectiveModeAsync: true,
  },
};

export const READ_OPERATING_GUIDE_TOOL = {
  name: "read_operating_guide",
  description:
    "Read the Purr Verify MCP operating guide. Call this before verification work so the agent uses smart execution routing, durable history, long-run workflows, and the correct repository tool boundary.",
  inputSchema: { type: "object", properties: {} },
  annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true },
};

const HEAVY_COMMAND_PATTERNS = [
  /\binstall\b/i,
  /\bbuild\b/i,
  /\blint\b/i,
  /\btypecheck\b/i,
  /\btest\b/i,
  /\bci\b/i,
  /\bprisma\s+generate\b/i,
  /\bplaywright\b/i,
  /\bcypress\b/i,
  /\bvitest\b/i,
  /\bjest\b/i,
  /\bsurfpool\s+start\b/i,
];

/** @deprecated Use execution-policy.ts resolveExecutionMode for routing decisions. */
export function findHeavySyncCommand(commands: unknown): string | null {
  if (!Array.isArray(commands)) return null;
  for (const command of commands) {
    if (typeof command !== "string") continue;
    if (HEAVY_COMMAND_PATTERNS.some((pattern) => pattern.test(command))) return command;
  }
  return null;
}
